### ISSUE TITLE
Matter oscillogram example does not work after renaming of functions

### ISSUE THREAD

**Issue by JMulder99** [KM3NeT/Neurthino.jl#12]
The example in `examples/matter_oscillogram.jl` does not work because some functions have been renamed in previous commits.

**Comment by JMulder99** [comment]
I made it such that the example is also run as a test, but that means it needs to add `Plots` as a test dependency. This makes the compiling before testing quite a bit longer, but it ensures a working example.

**Comment by tamasgal** [comment]
Ah, thanks Jelmer for taking care! I think it would be a good idea to include the example in the docs and add their `Plots.jl` as dependency (I'd rather prefer `CairoMakie`, but that's another topic 😆 )

**Comment by JMulder99** [comment]
NP, `Neurthino.jl` is great little package. Do you mean we should include the example file as a separate page in the docs, and can we then show the output? You already have the step by step example in the README. The `matter_oscillogram.jl` example is not very different as I see it.

**Comment by JMulder99** [comment]
In [JMulder99:make_example_work](https://github.com/JMulder99/Neurthino.jl/tree/make_example_work), I removed the example entirely and replaced it with an new page in the docs. When making the docs, it runs the code directly and includes the plots in the html output.

**Comment by JMulder99** [comment]
What should we do with the examples in the README?

Also, the use case of `U_mat, H_mat = MatterOscillationMatrices(U, H, 1, 13);` is a bit vague, because `Pνν` already converts them based on the paths you give.

**Comment by tamasgal** [comment]
Can you make a pull request? We can discuss there :) i hope to get @8me involved
